httpProxy: "http://127.0.0.1:1082"

httpsProxy: "http://127.0.0.1:1082"

npmAuditRegistry: "http://npm.zhaopin.com"

npmPublishRegistry: "http://npm.zhaopin.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

unsafeHttpWhitelist:
  - "*.zhaopin.com"
